@startuml

title Cas d'utilisation détaillé : Utiliser une technique de coloration (ex : H&E)

actor "Technicien de laboratoire" as TechLab
left to right direction
rectangle "Application Mobile TechLab Pro" {
    
    usecase UC1 as "Sélectionner le laboratoire"
    usecase UC2 as "Consulter les techniques"
    usecase UC3 as "Sélectionner la technique H&E"
    usecase UC4 as "Afficher les détails H&E"
    usecase UC5 as "Démarrer minuteries H&E"
    usecase UC6 as "Recevoir alertes/instructions"
    usecase UC7 as "Valider chaque étape"
    usecase UC8 as "Enregistrer la procédure"
    usecase EXT1 as "Alerte : réactif manquant"
    usecase EXT2 as "Alerte : dépassement de temps"
}

TechLab --> UC1
TechLab --> UC2
TechLab --> UC3
TechLab --> UC4
TechLab --> UC5
' TechLab --> UC6
' TechLab --> UC7
TechLab --> UC8

UC5 --> UC6 : <<include>>
UC6 --> UC7 : <<include>>

UC5 --> EXT1 : <<extend>>
UC6 --> EXT2 : <<extend>>

@enduml
