@startuml


class Utilisateur {
    id: int
    nom: String
    prenom: String
    email: String
    password: String
    telephone: String
}

class Technicien {
  id: int
}
class Stagiaire {
  id: int
}





class Affectation {
  date:String
}


package "Lab"{
  class Laboratoire {
  id: int
  titre: String
  image: String
  }
  class Prérequis {
      id: int
      nom: String
      description: String
  }
  class Etape {
      id: int
      Titre: String
      reactive:String
      duree: int
      description: String
  }
  class Conseil {
      id: int
      conseil: String
      description: String
  }
  class Categorie{
      id: int
      nom: String
      description: String
  }
  class Technique {
  id: int
  titre: String
  image: String
  description: String
  }
  class Etape_conseil
  {
    duree: int
  }
}
package "pkg_Quiz" {

  

  class Question{
      id: int
      texte:String
  }

  class Reponse{
      id: int
      texte:string
  }
  class Option
  {
    isCorrect: Boolean
  }

  class Quiz{
    id: int
    titre: String
    description: String
  }
}



' relations des utilisateurs(Héritage) :
Utilisateur <|-- Technicien
Utilisateur <|-- Stagiaire

' autre relations  :
Laboratoire "1..1" -- "0..*" Technique
Technicien "0..*" -- "0..*" Technique : favoris
Technicien "0..*" -- "0..*" Technique : Démarer
(Technicien, Technique) . Affectation
Prérequis "1..*" -- "0..*" Technique
Technicien "0..*" -- "1..1" Laboratoire
Categorie "1..1" -- "0..*" Technique
Etape "1..*" -- "0..*" Technique
Etape "0..*" -- "1..*" Conseil
(Etape, Conseil) . Etape_conseil

' relations Quiz
Question "0..*" -- "1..1" Quiz
Question "0..*" -- "0..*" Reponse
(Question, Reponse) . Option






@enduml